---
title: "YAP1 regulation in Meningioma"
output: html_notebook
author: Nayanga Thirimanne
date: "January 2024"
---
```{r}
library(tidyverse)
library(reshape)
```


Load data files
```{r}
vstcounts <- read_rds("~/XX/Output_VSTcounts/batchcor_vstcounts_1298.rds")
#vstcounts <- log2(vstcounts1+1)
sample_info <- readxl::read_excel("~/HollandLabShared/Meningioma_bulkrnaseq_datasets/Oncoscape_versions/DAM_data_clinical_patient_v40b_20240131.xlsx", skip = 5)
sample_info <- sample_info[-1, ]

clusterID <- read.csv("~/XX/Output_VSTcounts/DBSCAN/dbscan2D_un37_vst.csv")

```

ggplot2 specifications
```{r}
library(ggplot2)
library(ggpubr)
library(rstatix)
plot_title_size = 20
legend_pt_size = 4
axis_text_size = 25
axis_title_size = 25
legend_text_size = 15
spacing = 1
chosen_margin = c(0.5,1,0.5,1) #top,right,bottom,left
theme_grid_nolegend <- theme_bw()+
  theme(plot.title = element_text(hjust=0, vjust=0, lineheight=.8, face="bold", size=plot_title_size),
        plot.margin = unit(chosen_margin,"cm"),
        legend.text = element_text(size=legend_text_size),
        legend.key.height = unit(spacing,"cm"),
        legend.position = "none",
        legend.justification = "left",
        legend.title = element_blank())
font_size = 18
theme_grid_legend <- theme_bw()+
  theme(plot.title = element_text(hjust=0, vjust=0, lineheight=.8, face="bold", size=plot_title_size),
        legend.text = element_text(size=legend_text_size, face = "bold"),
        legend.key.height = unit(spacing,"cm"),
        legend.position = "top",
        legend.justification = "left",
        legend.title = element_blank()
        )
```

Violin plots to compare YAP1-related genes in clusters A, B, C and D
```{r}

clAB <- subset(clusterID, (clusterID$cluster == "A" | clusterID$cluster == "B"))
clCD <- subset(clusterID, (clusterID$cluster == "C" | clusterID$cluster == "D"))
clA <- subset(clusterID, clusterID$cluster == "A")
clB <- subset(clusterID, clusterID$cluster == "B")

clusterID_sub$AB[clusterID_sub$coordinate_ID %in% clAB$coordinate_ID] <- "AB"
clusterID_sub$CD[clusterID_sub$coordinate_ID %in% clCD$coordinate_ID] <- "CD"
clusterID_sub$A[clusterID_sub$coordinate_ID %in% clA$coordinate_ID] <- "A"
clusterID_sub$B[clusterID_sub$coordinate_ID %in% clB$coordinate_ID] <- "B"
clusterIDs <- clusterID_sub[,c("coordinate_ID", "AB", "CD", "A", "B")] 

gene = "CCN1"

CC <- pivot_longer(data = clusterIDs, cols =  c("AB", "CD", "A", "B")) %>% .[,-2] %>% na.omit(.)
colnames(CC)[2] <- "cluster"

VV <- vstcounts %>%
as.data.frame(.) %>%
  filter(., rownames(.) %in% gene) %>%
  t(.)  %>%
  as.data.frame(.) %>%
  rownames_to_column(., var = "coordinate_ID") %>%
  left_join(., CC, by = "coordinate_ID") %>% 
  na.omit(.)

colnames(VV)[2] <- "value"

VV %>% 
  ggplot(aes(x = cluster, y = value, fill = cluster)) +
  geom_violin( alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75)) +
  ylab("Counts") +
  xlab("Cluster") +
  scale_x_discrete(limits=c("CD", "AB", "B", "A")) +
  scale_fill_manual(values = c("red", "sienna1", "darkkhaki", "blue4")) +
  theme_grid_nolegend +
  theme(axis.title.x = element_text(size = 15, face = "bold")) +
  theme(axis.title.y = element_text(size = 15, face = "bold")) +
  theme(axis.text.x = element_text(size = 15, face = "bold", color = "black")) +
  theme(axis.text.y = element_text(size = 15, face = "bold", color = "black")) +
  theme(strip.text = element_text(size = 15, face = "bold")) 
  

```

Generate plots for multiple genes
```{r}
clAB <- subset(clusterID, (clusterID$cluster == "A" | clusterID$cluster == "B"))
clCD <- subset(clusterID, (clusterID$cluster == "C" | clusterID$cluster == "D"))
clA <- subset(clusterID, clusterID$cluster == "A")
clB <- subset(clusterID, clusterID$cluster == "B")

clusterID_sub$AB[clusterID_sub$coordinate_ID %in% clAB$coordinate_ID] <- "AB"
clusterID_sub$CD[clusterID_sub$coordinate_ID %in% clCD$coordinate_ID] <- "CD"
clusterID_sub$A[clusterID_sub$coordinate_ID %in% clA$coordinate_ID] <- "A"
clusterID_sub$B[clusterID_sub$coordinate_ID %in% clB$coordinate_ID] <- "B"
clusterIDs <- clusterID_sub[,c("coordinate_ID", "AB", "CD", "A", "B")] 
```

```{r}

gene = "CCN1"

my_violin_plot = function(gene){
  CC <- pivot_longer(data = clusterIDs, cols =  c("AB", "CD", "A", "B")) %>% .[,-2] %>% na.omit(.)
colnames(CC)[2] <- "cluster"

VV <- vstcounts %>%
as.data.frame(.) %>%
  filter(., rownames(.) %in% gene) %>%
  t(.)  %>%
  as.data.frame(.) %>%
  rownames_to_column(., var = "coordinate_ID") %>%
  left_join(., CC, by = "coordinate_ID") %>% 
  na.omit(.)

colnames(VV)[2] <- "value"

VV %>% 
  ggplot(aes(x = cluster, y = value, fill = cluster)) +
  geom_violin( alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75)) +
  ylab("Counts") +
  xlab("Cluster") +
  scale_x_discrete(limits=c("CD", "AB", "B", "A")) +
  scale_fill_manual(values = c("red", "sienna1", "darkkhaki", "blue4")) +
  theme_grid_nolegend +
  theme(axis.title.x = element_text(size = 15, face = "bold")) +
  theme(axis.title.y = element_text(size = 15, face = "bold")) +
  theme(axis.text.x = element_text(size = 15, face = "bold", color = "black")) +
  theme(axis.text.y = element_text(size = 15, face = "bold", color = "black")) +
  theme(strip.text = element_text(size = 15, face = "bold"))
  
}

```
`

```{r}
setwd("~XX")

genes <- c("VGLL1", "VGLL2", "VGLL3", "VGLL4", "NF2", "YAP1", "ANKRD1", "AMOTL2", "AMOT", "AMOTL1", "CITED2", "TEAD1", "TEAD2", "TEAD3", "TEAD4", "CCN1", "CCN2")

for (gene in genes) {
  pdf(paste0(gene, "_clustersABCD.pdf"), width = 6, height = 6)
  pq <- my_violin_plot(gene)
  print(pq)
  dev.off()

}

```

```{r}
setwd("~/XX")

genes <- c("FAT1", "FAT2", "FAT3", "FAT4", "LATS1", "LATS2", "STK3", "STK4", "DCHS1", "DCHS2", "MOB1A", "MOB1B",
           "TAOK1", "TAOK2", "TAOK3", "FRMD6", "SAV1", "WWC1", "WWTR1" )

for (gene in genes) {
  pdf(paste0(gene, "_clustersABCD.pdf"), width = 6, height = 6)
  pq <- my_violin_plot(genes)
  print(pq)
  dev.off()

}

```


Statistics to determine significant between CD vs AB, B vs A, CD vs B, CD vs A
```{r}

gene = "CCN1"

my_ttest = function(gene){
  CC <- pivot_longer(data = clusterIDs, cols =  c("AB", "CD", "A", "B")) %>% .[,-2] %>% na.omit(.)
colnames(CC)[2] <- "cluster"

VV <- vstcounts %>%
as.data.frame(.) %>%
  filter(., rownames(.) %in% gene) %>%
  t(.)  %>%
  as.data.frame(.) %>%
  rownames_to_column(., var = "coordinate_ID") %>%
  left_join(., CC, by = "coordinate_ID") %>% 
  na.omit(.)

colnames(VV)[2] <- "value"

cluster_A <- subset(VV, cluster == "A")
cluster_B <- subset(VV, cluster == "B")
cluster_AB <- subset(VV, cluster == "AB")
cluster_CD <- subset(VV, cluster == "CD")

t_test_A_B <- t.test(cluster_A$value, cluster_B$value)
t_test_AB_CD <- t.test(cluster_AB$value, cluster_CD$value)
t_test_CD_A <- t.test(cluster_CD$value, cluster_A$value)
t_test_CD_B <- t.test(cluster_CD$value, cluster_B$value)

}

```

```{r}
setwd("~/XX")

results_df <- data.frame(
  gene = character(),
  t_test_A_B.p.value = numeric(),
  t_test_AB_CD.p.value = numeric(),
  t_test_CD_A.p.value = numeric(),
  t_test_CD_B.p.value = numeric()
)

genes <- c("VGLL1", "VGLL2", "VGLL3", "VGLL4","NF2", "YAP1","ANKRD1", "AMOTL2", "AMOT", "AMOTL1", "CITED2", "TEAD1", "TEAD2", "TEAD3", "TEAD4", "CCN1", "CCN2")


for (gene in genes) {
  pq <- my_ttest(gene)
  results_df <- rbind(results_df, pq)
}

```


```{r}
write.csv(results_df, "~/XX")
```

